### ISSUE TITLE
抓取到的pt_pin是中文时，wskey转换脚本不能识别。

### ISSUE THREAD

**Issue by fichenx** [lzwme/whistle.x-scripts#1]
京东账户名是中文，抓取到的pt_pin，wskey转换脚本不能识别，导致无法转换，建议导入青龙环境变量时进行URL encode编码。

**Comment by renxia** [comment]
本仓库仅维护插件功能，您提到的某东 wskey 是具体的脚本规则问题，具体维护地址为：
https://github.com/lzwme/x-scripts-rules/blob/main/src/jd.js#L54

请等待该仓库更新，也可参考它编写本地规则覆盖它以更新

**Comment by fichenx** [comment]
多谢。
